### PR TITLE
Inline format text

### LINKED ISSUE #31: I can Select text inline and have slate buttons change status based on formatting of whats selected

### LINKED ISSUE #32: I can Format text on a text block using formatting on quanta toolbar (e.g. bold)
- there are paragraph formats (e.g. heading) and char formats (e..g bold). We can split out the paragraph formatting into a seperate card if it makes sense.
- The quanta toolbar has a different layout from slate. We can follow quanta or slate layout. If it's just as easy to follow quanta then follow that.
   - quanta groups all paragraph styles into a single dropdown. and keeps char styles as seperate buttons.

Tasks
- [x] Select adn turn something bold
- [x] select same text and unbold it
- [x] click bold and start typing bold
- [x] untoggle bold and now typing is not bold
- [x] add in italic and other styles

Edge cases
- [ ] select bold + normal text and then click bold
- [ ] select bold and italic next to each other and click bold
- [ ] ...

### LINKED ISSUE #88: I can click on a text field on a block and text formatting buttons will appear on the quanta toolbar

### PR DESCRIPTION
**Pull request by MAX-786**
fixes #88 
fixes #31 
fixes #32

Approach (still got some bugs) : 

**hydra.js:**

- [x] Adds a bold button in the toolbar.
- [x] Detects text selection within a block.
- [x] Sends the selected text information and cursor positions to the admin UI via postMessage.

**Admin UI:**

- [x] Receives the selection data and the bold state (active/inactive).
- [x] Updates the JSON data to reflect the bold formatting.
- [x] Sends the updated JSON data back to the iframe.

Since we have to write our own toggleMark method to update the json of selected block richtext field, I am doing the following:
- A deep copy of blockData is created to ensure the original data is not modified directly.
- findNode method to track the parent node (startNodeParent) where the updates should be applied.
- Nodes within the specified range are filtered out from startNodeParent.children. During this process, the index where the first node in the range was found (insertIndex) is recorded.
- The updatedNodes are inserted at the insertIndex, replacing the removed nodes while maintaining the order of the remaining nodes.

### CODE REVIEW

**Comment by MAX-786** [comment]
I think as Dylan suggested, its better to move addNodeIds on the adminUI side, which will lessen the load on hydrajs and also help us in formatting text inline.
I'll try it out and see how complicated it is to do so.

**Comment by djay** [comment]
@MAX-786 why do we care if the original data is modified? I don't think there is a way to cancel an inline edit is there?
does slate in the sidebar modify the original data?

Will you include the other char formatting as well in this PR? might as well include them if its easy. 
paragraph formats like h2 etc work different. are they better in a different PR or this one?

**Comment by djay** [comment]
Did it help to see the slate package and it's transform code?

**Comment by MAX-786** [comment]
Yep!!!! they helped and interestingly i was looking at them before too but i wasn't sure if it would be useful but i made them work and now i also added 'italic' & 'del' formats too. I'll be adding the comments with what approach i used and what it is actually doing to format the text.

**Comment by MAX-786** [comment]
https://github.com/user-attachments/assets/dcec3a20-3007-4355-b781-7eb62039605a

**Comment by djay** [comment]
@MAX-786 I think this looks good enough and we should get it merged and move on

**Comment by djay** [comment]
@MAX-786 does this work for #107 also or does this only work for the slate block?

**Comment by MAX-786** [comment]
> @MAX-786 does this work for https://github.com/collective/volto-hydra/issues/107 also or does this only work for the slate block?

inline text editing and realtime update is implemented by keeping in mind the instructions for integrator in readme so it will work but inline formatting is currently supported for slate blocks only.

**Review by djay — APPROVED** [review]
seems to work well.
I notice there seems to be some lag but thats something that can be optimised later

**Pull request merged**
