### PR TITLE
Added the ability to use the image block URL field from the sidebar

### LINKED ISSUE #19: I can Add media (images, videos etc.) in sidebar to store them on backend.

### LINKED ISSUE #22: I can See image block show image in preview when images added in sidebar

### PR DESCRIPTION
**Pull request by MAX-786**
Blocked by #75

Fixes #22 
Fixes #19 

@JeffersonBledsoe I added `widget: image` as you said but it is giving me a input field only (pasting there a url works) not like the you shown in discord. Do i need to use `widget:object_browser` for that? but using that breaks the site.

### CODE REVIEW

**Comment by JeffersonBledsoe** [comment]
@MAX-786 We're waiting on a Volto release for this widget, good planning ahead though :) I'll update this PR as soon as the release is out and you can give it a test then?

**Comment by MAX-786** [comment]
Ohkk sure sure, so we are putting this PR nd issue at hold till then right?

**Comment by JeffersonBledsoe** [comment]
> Ohkk sure sure, so we are putting this PR nd issue at hold till then right?

Yep. I've updated this PR description to highlight that.

**Comment by JeffersonBledsoe** [comment]
Merging this so the functionality is partially there, the fixes for the 'Upload directly from sidebar' will be tracked by #76

**Pull request merged**
