### PR TITLE
Select/Enter frontend URL under "pereferences"

### LINKED ISSUE #89: Add "frontend" under "preferences" which lets you pick from one of many frontends pre-registered or type-in your own URL.
Add "frontend" under "preferences" which lets you pick from one of many frontends pre-registered or type-in your own URL. It should be clear this is the "base" url and paths are added onto the end to get to content.

340768694-c782f8a2-6f5e-4715-b48e-db281a8b45fa

### PR DESCRIPTION
**Pull request by MAX-786**
Fixes #89 

You can,

- Click on "Personal Tools" and go to "Preferences" to select your frontend URL from preset urls and hit save to load your frontend.
- OR you can check on "Enter Your Frontend's URL" to open input field and type in your frontend URL and hit save to load it, and if the URL is invalid it will popup the toast error message. 
- Enter your new frontend url, hit save, then it will be saved in cookies and next time you can select it from options.

Current Design [Updated]:
- Now URL input is not taking up the screen and breadcrumbs are gone too.
- Still using the custom URL toggle. (Future fix maybe)

https://github.com/collective/volto-hydra/assets/99530996/07fe443f-6f9d-4a77-9a28-3b39e2d9a8d3

### CODE REVIEW

**Comment by MAX-786** [comment]
@djay The other UI design i have for this is to move both fields into their own tab namely "Frontend" like in below screenshot or we can leave it as it is shown above.

Alternative design:
Screenshot from 2024-07-02 22-15-39

**Comment by JeffersonBledsoe** [comment]
@MAX-786 I think I prefer the first design. I would change "Select Frontend URL" to "Frontend URL" and change the description to say something like "Changes the site to visit when in edit mode". I would also not have the toggle there and have the text input always visible with something like "Override URL" or "Custom URL" as the title and have the description mention that it overrides the selected URL if entered.

**Comment by MAX-786** [comment]
@JeffersonBledsoe sure, I will update the titles
> I would also not have the toggle there and have the text input always visible with something like "Override URL" or "Custom URL" as the title and have the description mention that it overrides the selected URL if entered.

The purpose of toggle is that it shows you can either SELECT OR INPUT only (I also moved toggle at last so the ui won't move a lot) , we can also write this in description but having a toggle, IMHO i don't see any downside of it. It also saves us from having a scenario when user selected a url AND also typed in a url (valid/invalid) and then hit submit, then how we make a decision that which url should be picked.

**Comment by djay** [comment]
I think you are probably.right about the toggle making it more clear. 
Space is not an problem at this point..
The only other way is a select widget that lets you pick or add which is more space efficient and only allows one url at a time.

**Comment by MAX-786** [comment]
> The only other way is a select widget that lets you pick or add which is more space efficient and only allows one url at a time.

Yepp, and as for now we do not have such widget in volto. I'll look into if it's feasible and fits in our timeline to develop our own widget like this. Till then IG we can go with this approach.

**Comment by MAX-786** [comment]
@djay Sorry but can you please share a link like in volto demo site, where this widget is used.. bcz i tried looking and couldn't find it :smiling_face_with_tear:

**Comment by djay** [comment]
Not sure if it can be made single select however
image

**Comment by MAX-786** [comment]
@djay @JeffersonBledsoe Checkout above updated comment for latest design

**Comment by djay** [comment]
@MAX-786 make a new comment with a new video otherwise it's confusing what comments refer to?

**Comment by MAX-786** [comment]
Current Design [Updated]:
- Now URL input is not taking up the screen and breadcrumbs are gone too.
- Still using the custom URL toggle. (Future fix maybe)


https://github.com/collective/volto-hydra/assets/99530996/92e95391-af19-4787-8da1-834d462e1b99

**Comment by djay** [comment]
@MAX-786 not sure where the bit of gap at the top is coming from. But it's good enough.
Only thing thats missing is an an update to the readme to explain where to go to change or enter a new frontend

**Comment by MAX-786** [comment]
@djay I think having a separate section like "Managing multiple frontends" makes sense.
Updated the readme with instructions

**Comment by MAX-786** [comment]
@JeffersonBledsoe I am ready to merge this, if it looks good to you too?

**Review by JeffersonBledsoe — CHANGES_REQUESTED** [review]
@MAX-786 You need to add the `PersonalPreferences.original.jsx` for the shadow and to document in the code what changed

**Review by JeffersonBledsoe — APPROVED** [review]
Looks fine to me now :)

**Pull request merged**
